id: A0E3404AA
base_file: fE221.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:45:14.110373
  last_modified_at: 2022-05-30 21:45:14.110377
